# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

XLQR <- function(ql, rtl, xl) {
    .Call('_LargeScaleLinReg_XLQR', PACKAGE = 'LargeScaleLinReg', ql, rtl, xl)
}

rcpparma_hello_world <- function() {
    .Call('_LargeScaleLinReg_rcpparma_hello_world', PACKAGE = 'LargeScaleLinReg')
}

rcpparma_outerproduct <- function(x) {
    .Call('_LargeScaleLinReg_rcpparma_outerproduct', PACKAGE = 'LargeScaleLinReg', x)
}

rcpparma_innerproduct <- function(x) {
    .Call('_LargeScaleLinReg_rcpparma_innerproduct', PACKAGE = 'LargeScaleLinReg', x)
}

rcpparma_bothproducts <- function(x) {
    .Call('_LargeScaleLinReg_rcpparma_bothproducts', PACKAGE = 'LargeScaleLinReg', x)
}

